name: cfn-lint

on:
  push:
    branches: [main]
    paths:
      - "cloudformation/**"
      - ".github/workflows/cfn-lint.yml"
  pull_request:
    branches: [main]
    paths:
      - "cloudformation/**"
      - ".github/workflows/cfn-lint.yml"

jobs:
  cfn-lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: "3.11"
      - run: pip install cfn-lint
      - run: cfn-lint cloudformation/*.yml
